name: Trigger auto deployment for app-test-oidc3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/app-test-oidc3-AutoDeployTrigger-84930329-ec1e-4db7-b044-b2da1115fba3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APPTESTOIDC3_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPTESTOIDC3_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPTESTOIDC3_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: registrytestoidc.azurecr.io
          registryUsername: ${{ secrets.APPTESTOIDC3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPTESTOIDC3_REGISTRY_PASSWORD }}
          containerAppName: app-test-oidc3
          resourceGroup: test
          imageToBuild: registrytestoidc.azurecr.io/app-test-oidc3:${{ github.sha }}
          dockerfilePath: Dockerfile


