name: Trigger auto deployment for cd-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/cd-test-AutoDeployTrigger-64fd16d3-5d9f-411d-bc97-510f519e6cbc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CDTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CDTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CDTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: continuousdeploymenttestregisrty.azurecr.io
          registryUsername: ${{ secrets.CDTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CDTEST_REGISTRY_PASSWORD }}
          containerAppName: cd-test
          resourceGroup: Testing
          imageToBuild: continuousdeploymenttestregisrty.azurecr.io/cd-test:${{ github.sha }}
          dockerfilePath: Dockerfile


