name: Trigger auto deployment for cont-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/cont-service-AutoDeployTrigger-ce960373-9340-4c2e-a762-8572e0800149.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTSERVICE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: antuxtest.azurecr.io
          registryUsername: ${{ secrets.CONTSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTSERVICE_REGISTRY_PASSWORD }}
          containerAppName: cont-service
          resourceGroup: OGFs220-0708-gayathri
          imageToBuild: antuxtest.azurecr.io/continuous-deployment-test-app:${{ github.sha }}
          dockerfilePath: Dockerfile

     

