name: Trigger auto deployment for continuous-deployment-test-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/continuous-deployment-test-app-AutoDeployTrigger-5b724f64-b3d3-4b7b-b4f9-a7eda03b2a8b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTINUOUSDEPLOYMENTTESTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTINUOUSDEPLOYMENTTESTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTINUOUSDEPLOYMENTTESTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: [reference(resourceId('Microsoft.ContainerRegistry/registries/', parameters('containerRegistryName')), '2022-02-01-preview', 'Full').properties.loginServer]
          registryUsername: ${{ secrets.CONTINUOUSDEPLOYMENTTESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTINUOUSDEPLOYMENTTESTAPP_REGISTRY_PASSWORD }}
          containerAppName: continuous-deployment-test-app
          resourceGroup: continuous-deployment-tests-rg
          imageToBuild: [reference(resourceId('Microsoft.ContainerRegistry/registries/', parameters('containerRegistryName')), '2022-02-01-preview', 'Full').properties.loginServer]/continuous-deployment-test-app:${{ github.sha }}
          dockerfilePath: Dockerfile


