name: Trigger auto deployment for deployment-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/worker/**'
    - '.github/workflows/deployment-test-AutoDeployTrigger-d5210486-3b37-4cad-be01-8252e5014902.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEPLOYMENTTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEPLOYMENTTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEPLOYMENTTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/worker 
          registryUrl: continuoustestregistry.azurecr.io
          registryUsername: ${{ secrets.DEPLOYMENTTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEPLOYMENTTEST_REGISTRY_PASSWORD }}
          containerAppName: deployment-test
          resourceGroup: ContinuousTests
          imageToBuild: continuoustestregistry.azurecr.io/deployment-test:${{ github.sha }}
          dockerfilePath: Dockerfile


