name: Trigger auto deployment for final-oidc-app2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/final-oidc-app2-AutoDeployTrigger-253fa0b0-b05a-4fae-856b-d950bff503ad.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FINALOIDCAPP2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FINALOIDCAPP2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FINALOIDCAPP2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: finaloidcregistry.azurecr.io
          registryUsername: ${{ secrets.FINALOIDCAPP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FINALOIDCAPP2_REGISTRY_PASSWORD }}
          containerAppName: final-oidc-app2
          resourceGroup: final-oidc-rg
          imageToBuild: finaloidcregistry.azurecr.io/final-oidc-app2:${{ github.sha }}
          dockerfilePath: Dockerfile


