name: Trigger auto deployment for oidc-app3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/oidc-app3-AutoDeployTrigger-16093b73-70b2-4d85-84c7-3e9ac72ab02a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.OIDCAPP3_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OIDCAPP3_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OIDCAPP3_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: oidcreg2.azurecr.io
          registryUsername: ${{ secrets.OIDCAPP3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OIDCAPP3_REGISTRY_PASSWORD }}
          containerAppName: oidc-app3
          resourceGroup: brip
          imageToBuild: oidcreg2.azurecr.io/oidc-app3:${{ github.sha }}
          dockerfilePath: Dockerfile


