name: Trigger auto deployment for oidctestcontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/oidctestcontainerapp-AutoDeployTrigger-3c0d7668-5b63-48e4-bfbb-1b9e95a9372e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.OIDCTESTCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OIDCTESTCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OIDCTESTCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: oidctestregistry.azurecr.io
          registryUsername: ${{ secrets.OIDCTESTCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OIDCTESTCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: oidctestcontainerapp
          resourceGroup: Testing
          imageToBuild: oidctestregistry.azurecr.io/oidctestcontainerapp:${{ github.sha }}
          dockerfilePath: Dockerfile


